baseURL = 'https://millman.us/'
languageCode = 'en-us'
title = 'David L Millman'
[params]
    cv = "./docs/millman-cv.pdf"
    bibtex = "./docs/millman.bib"
    colophon = "/colophon/"

[params.social]
    email = "dave@millman.us"
    orcid = "0000-0003-4112-3026"
    linkedin = "dlm0"
    github = "dlm"
    googlescholar = "UkEzX6UAAAAJ"
    twitter = "dlmillman"

[markup.highlight]
    style = "catppuccin-frappe"

[[menus.main]]
    name = "About"
    pageRef = "/"
    weight = 1

[[menus.main]]
    name = "Projects"
    pageRef = "/projects"
    weight = 10

[[menus.main]]
    name = "Writing"
    pageRef = "/blog"
    weight = 30

[[menus.footer]]
    name = "CV"
    url = "./docs/millman-cv.pdf"
    weight = 10

[[menus.footer]]
    name = "Publications"
    url = "./docs/millman.bib"
    weight = 20

[[menus.footer]]
    name = "Colophon"
    pageRef = "/colophon/"
    weight = 30
