baseURL = 'https://millman.us/'
languageCode = 'en-us'
title = 'David L Millman'
[params]
    tagline = 'Some wity tagline'


[[menus.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menus.main]]
    name = "Research"
    url = "/research/"
    weight = 10

[[menus.main]]
    name = "CV"
    url = "/cv/"
    weight = 20

[[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30
