baseURL = 'https://millman.us/'
languageCode = 'en-us'
title = 'David L Millman'
[params]
    tagline = 'Some wity tagline'

[params.social]
    email = "dave@millman.us"
    orcid = "0000-0003-4112-3026"
    linkedin = "dlm0"
    github = "dlm"
    googlescholar = "UkEzX6UAAAAJ"
    twitter = "dlmillman"

[markup.highlight]
    style = "catppuccin-frappe"

[[menus.main]]
    name = "About"
    pageRef = "/"
    weight = 1

[[menus.main]]
    name = "Research"
    pageRef = "/research"
    weight = 10

[[menus.main]]
    name = "CV"
    pageRef = "/cv"
    weight = 20

[[menus.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 30
