baseURL = 'https://millman.us/'
languageCode = 'en-us'
title = 'David L Millman'
[params]
    tagline = 'Some wity tagline'

[params.social]
    email = "dave@millman.us"
    orcid = "0000-0003-4112-3026"
    linkedin = "dlm0"
    github = "dlm"
    googlescholar = "UkEzX6UAAAAJ"
    twitter = "dlmillman"


[[menus.main]]
    name = "About"
    url = "/"
    weight = 1

[[menus.main]]
    name = "Research"
    url = "/research/"
    weight = 10

[[menus.main]]
    name = "CV"
    url = "/cv/"
    weight = 20

[[menus.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30
